runtime: php
env: flex

runtime_config: 
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 20

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:pu0vEiH/s04q5pVHr6lWISGsxEV4No8Ne5WNJfGCqII=
    APP_NAME: "Remunerasi"

    LOG_LEVEL: debug

    DB_CONNECTION: mysql
    DB_HOST: 34.101.217.171
    DB_PORT: 3306
    DB_DATABASE: rsud_genteng
    DB_USERNAME: root
    DB_PASSWORD: BlG70UsL>S8SH7On
